spring:
  application:
    name: spring-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always


  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xubo
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver




logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.bluebridge.ai: DEBUG
